export const SCHOOL_CONFIG = {
  ETH: {
    name: "ETH Zürich",
    primary: "#1A5276",
    primaryLight: "#D6EAF8",
    primaryText: "#1A5276",
    accent: "#2980B9",
    bg: "#EBF5FB",
    badge: "bg-blue-900 text-white",
    button: "bg-blue-900 hover:bg-blue-800",
    tab: "bg-blue-900",
  },
  EPFL: {
    name: "EPFL",
    primary: "#C0392B",
    primaryLight: "#FADBD8",
    primaryText: "#C0392B",
    accent: "#E74C3C",
    bg: "#FDEDEC",
    badge: "bg-red-700 text-white",
    button: "bg-red-700 hover:bg-red-600",
    tab: "bg-red-700",
  },
  UNIZH: {
    name: "Uni Zürich",
    primary: "#1A6FA8",
    primaryLight: "#D6EAF8",
    primaryText: "#1A6FA8",
    accent: "#2980B9",
    bg: "#EBF5FB",
    badge: "bg-sky-700 text-white",
    button: "bg-sky-700 hover:bg-sky-600",
    tab: "bg-sky-700",
  },
  UNIBASEL: {
    name: "Uni Basel",
    primary: "#7D3C98",
    primaryLight: "#E8DAEF",
    primaryText: "#7D3C98",
    accent: "#8E44AD",
    bg: "#F4ECF7",
    badge: "bg-purple-700 text-white",
    button: "bg-purple-700 hover:bg-purple-600",
    tab: "bg-purple-700",
  },
  UNIBE: {
    name: "Uni Bern",
    primary: "#C0392B",
    primaryLight: "#FADBD8",
    primaryText: "#C0392B",
    accent: "#E74C3C",
    bg: "#FDEDEC",
    badge: "bg-red-700 text-white",
    button: "bg-red-700 hover:bg-red-600",
    tab: "bg-red-700",
  },
  UNIL: {
    name: "Uni Lausanne",
    primary: "#1E8449",
    primaryLight: "#D5F5E3",
    primaryText: "#1E8449",
    accent: "#27AE60",
    bg: "#EAFAF1",
    badge: "bg-green-700 text-white",
    button: "bg-green-700 hover:bg-green-600",
    tab: "bg-green-700",
  },
  UNIFR: {
    name: "Uni Fribourg",
    primary: "#922B21",
    primaryLight: "#FADBD8",
    primaryText: "#922B21",
    accent: "#C0392B",
    bg: "#FDEDEC",
    badge: "bg-red-800 text-white",
    button: "bg-red-800 hover:bg-red-700",
    tab: "bg-red-800",
  },
  UNIGE: {
    name: "Uni Genève",
    primary: "#148F77",
    primaryLight: "#D1F2EB",
    primaryText: "#148F77",
    accent: "#1ABC9C",
    bg: "#E8F8F5",
    badge: "bg-teal-700 text-white",
    button: "bg-teal-700 hover:bg-teal-600",
    tab: "bg-teal-700",
  },
  UNISG: {
    name: "Uni St. Gallen",
    primary: "#1B2631",
    primaryLight: "#D5D8DC",
    primaryText: "#1B2631",
    accent: "#2C3E50",
    bg: "#EAECEE",
    badge: "bg-slate-800 text-white",
    button: "bg-slate-800 hover:bg-slate-700",
    tab: "bg-slate-800",
  },
  USI: {
    name: "USI Lugano",
    primary: "#CA6F1E",
    primaryLight: "#FDEBD0",
    primaryText: "#CA6F1E",
    accent: "#E67E22",
    bg: "#FEF9E7",
    badge: "bg-orange-600 text-white",
    button: "bg-orange-600 hover:bg-orange-500",
    tab: "bg-orange-600",
  },
  UNILU: {
    name: "Uni Lucerne",
    primary: "#0E6655",
    primaryLight: "#D1F2EB",
    primaryText: "#0E6655",
    accent: "#16A085",
    bg: "#E8F8F5",
    badge: "bg-teal-800 text-white",
    button: "bg-teal-800 hover:bg-teal-700",
    tab: "bg-teal-800",
  },
};

export const DEFAULT_SCHOOL = {
  name: "fizz",
  primary: "#7C3AED",
  primaryLight: "#EDE9FE",
  primaryText: "#7C3AED",
  accent: "#6D28D9",
  bg: "#F5F3FF",
  badge: "bg-violet-600 text-white",
  button: "bg-violet-600 hover:bg-violet-700",
  tab: "bg-violet-600",
};

export function getSchoolConfig(school) {
  return SCHOOL_CONFIG[school] || DEFAULT_SCHOOL;
}